model_list:
  - model_name: "vercel_ai_gateway/*"
    litellm_params:
      model: "vercel_ai_gateway/*"
      api_key: os.environ/VERCEL_AI_GATEWAY_API_KEY

  - model_name: "anthropic/*"
    litellm_params:
      model: "vercel_ai_gateway/anthropic/*"
      api_key: os.environ/VERCEL_AI_GATEWAY_API_KEY

  - model_name: "openai/*"
    litellm_params:
      model: "vercel_ai_gateway/openai/*"
      api_key: os.environ/VERCEL_AI_GATEWAY_API_KEY

  - model_name: "xai/*"
    litellm_params:
      model: "vercel_ai_gateway/xai/*"
      api_key: os.environ/VERCEL_AI_GATEWAY_API_KEY

  - model_name: "google/*"
    litellm_params:
      model: "vercel_ai_gateway/google/*"
      api_key: os.environ/VERCEL_AI_GATEWAY_API_KEY

  - model_name: "google/gemini-embedding-2"
    litellm_params:
      model: "vercel_ai_gateway/google/gemini-embedding-2"
      api_key: os.environ/VERCEL_AI_GATEWAY_API_KEY
      input_cost_per_token: 0.0000002 # $0.20 / 1M

litellm_settings:
  callbacks: clickhouse_logger.clickhouse_logger
  drop_params: true
  set_verbose: false

general_settings:
  custom_auth: auth.user_api_key_auth
